### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by handy-git** [Rosewood-Development/PlayerParticles#109]
addActivePlayerParticle​(@NotNull org.bukkit.entity.Player player, @NotNull ParticleEffect effect, @NotNull ParticleStyle style, @NotNull OrdinaryColor colorData)

colorData  invalid

**Comment by Esophose** [comment]
Could you post the code you used?

**Comment by handy-git** [comment]
> Could you post the code you used?

OrdinaryColor color = new OrdinaryColor(66, 120, 150);
            PlayerParticlesAPI.getInstance().addActivePlayerParticle(player,ParticleEffect.DUST,ParticleStyle.fromName("CUBE"),color);
