### ISSUE TITLE
[Feature Request] Location based particle effects

### ISSUE THREAD

**Issue by LadyHaley** [Rosewood-Development/PlayerParticles#110]
I love this plugin and have used it for a few years now. one feature i need on my server is a location particles plugin, and there have been a few over the years but they all just end up fading away and become abandoned. Its a little bit out of the scope of the current plugin but location particles could be a really useful addition, and with players being allowed to disable and enable seeing particles made by the plugin, it would further the goal of player control over what they do and dont see.

it would be helpful for adding decoration to a spawn area or some minigame maps, but adittionally, players can use them to decorate their builds without needing staff intervetion as previous location particles have required

**Comment by Esophose** [comment]
This already exists as the `/pp fixed` command, is that what you wanted?

**Comment by LadyHaley** [comment]
That is what I was looking for!!! Tho it would be pretty epic if players could create and manage their own fixed particles in a similar manner to their player particles
