### ISSUE TITLE
Vanish support

### ISSUE THREAD

**Issue by LeonMangler** [Rosewood-Development/PlayerParticles#117]
Hello,
I'm the dev of the SuperVanish and PremiumVanish plugins and I have heard from a customer that the vanish integration of PlayerParticles may not be working. I checked the source code and am wondering if perhaps you forgot to add a negation at the end of the isPlayerVisible check. Currently it seems like players would be considered visible rather than invisible when the vanished metadata is present.

Here's the line I'm looking at:
https://github.com/Rosewood-Development/PlayerParticles/blob/c680a2bf9797b0434b702fbe427a5a1fea1e0f3f/src/main/java/dev/esophose/playerparticles/util/ParticleUtils.java#L161

In case it is indeed a mistake I would be really thankful if it could be fixed!

**Comment by TwoPointInfinity** [comment]
This would be great to have fixed.

**Comment by Esophose** [comment]
Sorry this took so long.. yes you are correct and this is fixed as of 95d74fd2cc6b296f2d652c0ee29d29644a44ee8b
