### ISSUE TITLE
Add a way to define fixed particle ownership to server.

### ISSUE THREAD

**Issue by mibby** [Rosewood-Development/PlayerParticles#72]
RE: https://github.com/Esophose/PlayerParticles/issues/70#issuecomment-775843815

Add a way to set fixed particles with an owner type of ``server`` so server-specific fixed particle locations avoid permission checks for removal and have no way of being deleted if testing group permissions.

**Comment by Esophose** [comment]
Just an FYI that it is already possible to create fixed effects from the console. I'll mark this as an enhancement but am not sure if I'll add it any time soon.

**Comment by Esophose** [comment]
Closing this as it's quite old and I'd prefer just having people use the console to do that.
