### ISSUE TITLE
NoClassDefFoundError: org/bstats/bukkit/MetricsLite

### ISSUE THREAD

**Issue by basedAF** [Rosewood-Development/PlayerParticles#81]
Metrics lite not shading in properly?

11.07 22:36:38 [Server] ERROR Error occurred while enabling PlayerParticles v7.20 (Is it up to date?)
11.07 22:36:38 [Server] INFO java.lang.NoClassDefFoundError: org/bstats/bukkit/MetricsLite
11.07 22:36:38 [Server] INFO at dev.esophose.playerparticles.PlayerParticles.onEnable(PlayerParticles.java:76) ~[?:?]
11.07 22:36:38 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
11.07 22:36:38 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.MetricsLite
11.07 22:36:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-83]
11.07 22:36:38 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-83]

**Comment by Esophose** [comment]
Was this a manual build? Try running `gradlew clean build` and see if that works. The last build with the current files succeeded on the Jenkins server.
