### ISSUE TITLE
[Feature Request] Use player selectors in the /ppo command run from command blocks

### ISSUE THREAD

**Issue by GhostIsBeHere** [Rosewood-Development/PlayerParticles#96]
I would like to be able to change a player's particles from a command block or a datapack. This would probably just look like being able to run /ppo from a command block or datapack.

**Comment by Esophose** [comment]
Does that command not already work through a command block? There shouldn't be anything preventing it from working since I know it can be run from console

**Comment by GhostIsBeHere** [comment]
It did not work from a command block when I tried to run it

**Comment by Esophose** [comment]
Just tested with v8.2, the /ppo command definitely works in command blocks

**Comment by Esophose** [comment]
Reopening as it doesn't actually allow the use of selectors for finding a player which means you can't use things like `@s`, I'll get that added.

**Comment by Esophose** [comment]
Added in 39744fa765b162cfe885e60a0f917788660c0d87
