### ISSUE TITLE
Ability to "stack" particle presets.

### ISSUE THREAD

**Issue by RealTriassic** [Rosewood-Development/PlayerParticles#97]
Currently, you can only select one preset at a time, selecting a different preset will clear the previous one, this really isn't ideal unless you're willing to give your players access to all styles and effects. I myself use presets just to not give my players access to all of them.

**Comment by RealTriassic** [comment]
Also, if stacking does get added, I believe it might be good to add an option to only allow stacking one style type of each, so for example, if I were to select an arrow effect, selecting another one would overwrite the previous option, but I will still be able to select Sword effects.

**Comment by Esophose** [comment]
Added in f595714535f64c0825ce03c984babeec3eb29f72
