### ISSUE TITLE
Ability to allow items in preset group to take free slots.

### ISSUE THREAD

**Issue by RealTriassic** [Rosewood-Development/PlayerParticles#98]
Currently, if you use `allow-permission-override: true` and give a player permission for one of the preset items that just so happens to not be the first item in the GUI, it will display it in the exact slot you defined it in, this is intentional behavior obviously, but it doesn't exactly look the prettiest.

![image](https://user-images.githubusercontent.com/40073455/198392591-f1672bb3-091d-41af-967a-f9b87872695d.png)

Suggestion: Let us not define the slot and instead dynamically determine the slot the item should be placed in so it is displayed in the first available slot instead of the pre-defined one.

**Comment by Esophose** [comment]
Added in 7ea6df06cf2f8e79c2edf1af6dcfba7a3c311aaa
