### ISSUE TITLE
Celebration style particles persists in vanish

### ISSUE THREAD

**Issue by SiuanSong** [Rosewood-Development/PlayerParticles#99]
Celebration style particles persists in vanish mode.  I tried both PremiumVanish and EssentialsX vanish, the particles persist in each instance.

Purpur 1.19.2 #1832
PlayerParticles 8.2

**Comment by Esophose** [comment]
If you would like the jar early it is available here https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/PlayerParticles/12/artifact/build/libs/PlayerParticles-8.3-SNAPSHOT.jar
